version: '3'


volumes:
#  grafana_lib: {}
  prometheus_data: {}
#  prometheus_config:
#    driver_opts:
#      type: tmpfs
#      device: tmpfs

services:
  web:
    build: .
    ports:
        - 5000
#    expose:
#        - 9323
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis
    ports:
        - 6379:6379
    links:
      - web
      - redis_exporter
    networks:
      - back-tier

  redis_exporter:
    image: oliver006/redis_exporter
    ports:
        - 9121:9121
    command: "-redis.addr='redis://redis:6379'"
    networks:
      - back-tier

  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - web
    networks:
      - front-tier
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

  prometheus:
    image: prom/prometheus:v2.1.0
    ports:
      - 9090:9090
    networks:
      - front-tier
      - back-tier
    volumes:
      - prometheus_data:/prometheus
#      - prometheus_config:/fragments/
      - ${PWD}/prometheus-server:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
#      - '--alertmanager.url=alertmanager:9093'

  grafana:
    image: grafana/grafana:5.1.3
    ports:
      - 3000:3000
    networks:
      - back-tier
#    volumes:
#      - grafana_lib:/var/lib/grafana
#      - ${PWD}/prometheus-server/config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret

  alertmanager:
    image: prom/alertmanager:v0.14.0
    ports:
      - 9093:9093
    networks:
      - back-tier
    command:
      - '--log.level=debug'
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    volumes:
      - ${PWD}/alertmanager-server:/etc/alertmanager/


networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
