version: '3'


volumes:
  grafana_data: {}
  prometheus_data: {}
  alertmanager_data: {}
services:
  web:
    build: .
    ports:
        - 5000
    networks:
      - front-tier
      - back-tier
    restart: always

  redis:
    image: redis
    ports:
        - 6379:6379
    links:
      - web
      - redis_exporter
    networks:
      - back-tier
    restart: unless-stopped

  redis_exporter:
    image: oliver006/redis_exporter
    ports:
        - 9121:9121
    command: "-redis.addr='redis://redis:6379'"
    networks:
      - back-tier
    restart: always

  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - web
    networks:
      - front-tier
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: always

  prometheus:
    image: prom/prometheus:v2.1.0
    ports:
      - 9090:9090
    networks:
      - front-tier
      - back-tier
    volumes:
      - prometheus_data:/prometheus
      - ${PWD}/prometheus-server:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always

  grafana:
    image: grafana/grafana:4.6.3
    ports:
      - 3000:3000
    networks:
      - back-tier
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always




  alertmanager:
    image: prom/alertmanager:v0.14.0
    ports:
      - 9093:9093
    networks:
      - back-tier
    command:
      - '--log.level=debug'
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - ${PWD}/alertmanager-server:/etc/alertmanager/
      - alertmanager_data:/alertmanager
    restart: always

  unsee:
    image: cloudflare/unsee:v0.8.0
    ports:
      - 9095:9095
    networks:
      - back-tier
    environment:
      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"
      - "PORT=9095"
    restart: always

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
