global:
  scrape_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
- /etc/prometheus/alerts/*

scrape_configs:
  - job_name: 'web'
    dns_sd_configs:
    - names:
      - 'web'
      type: 'A'
      port: 8000
  - job_name: 'redis'
    dns_sd_configs:
    - names:
      - 'redis_exporter'
      type: 'A'
      port: 9121
  - job_name: 'prometheus'
    dns_sd_configs:
    - names:
      - 'prometheus'
      type: 'A'
      port: 9090
  - job_name: 'grafana'
    dns_sd_configs:
    - names:
      - 'grafana'
      type: 'A'
      port: 3000
  - job_name: 'alertmanager'
    dns_sd_configs:
    - names:
      - 'alertmanager'
      type: 'A'
      port: 9093

